apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: default
spec:
  selector:
    matchLabels:
      app: php-apache
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: gcr.io/google_containers/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
  namespace: default
spec:
  selector:
      app: php-apache
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
