ARG PLATFORM
FROM --platform=linux/${PLATFORM} amazoncorretto:11

COPY ./target/hello.jar /app/demo.jar
COPY ./agents/aws-opentelemetry-agent.jar /app/otel.jar
COPY ./agents/opentelemetry-jmx-metrics.jar /app/jmx.jar
COPY ./agents/session.properties /app/session.properties
COPY ./start-ecs-docker.sh /app/start-ecs-docker.sh
# WORKDIR /app
ENTRYPOINT ["bash", "/app/start-ecs-docker.sh"]