apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hello
  name: hello
  namespace: default
#  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::996599195919:role/xray_default_role_demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
#  namespace: default
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: hello
  name: hello
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: namespace-reader
subjects:
    - kind: ServiceAccount
      name: hello
      namespace: default